### ISSUE TITLE
Can’t find mbed-block

### ISSUE THREAD

**Issue by sander** [ARMmbed/ble-ancs-client#1]
I’m trying to compile ancs-client-demo locally using a custom `CMakeLists.txt` and I can’t find a repository for the mbed-block dependency. Is it still private?

**Comment by rgrover** [comment]
Can you be specific what you mean by the  `mbed-block` dependency?

**Comment by sander** [comment]
Oops, yes, sorry. This is the error I’m getting:

```
$ make
Scanning dependencies of target PROJECT.elf
[  0%] Building CXX object CMakeFiles/PROJECT.elf.dir/ANCSClient.cpp.o
In file included from /Users/sander/Code/nRF51/projects/ancs-client-demo/ANCSClient.cpp:17:0:
/Users/sander/Code/nRF51/projects/ancs-client-demo/ANCSClient.h:25:37: fatal error: mbed-block/BlockDynamic.h: No such file or directory
 #include "mbed-block/BlockDynamic.h"
                                     ^
compilation terminated.
make[2]: *** [CMakeFiles/PROJECT.elf.dir/ANCSClient.cpp.o] Error 1
make[1]: *** [CMakeFiles/PROJECT.elf.dir/all] Error 2
make: *** [all] Error 2
```

Most of the time I can fix these kind of errors by searching for the specific file (in this case `mbed-block/BlockDynamic.h`), but this one I can’t find either on my pc or in any GitHub repository. Right now I’m compiling with files from the `mbed`, `ble`, `core-util`, `ualloc`, and `ble-nrf51822` repositories. Hence the question whether I was missing a repository that provides `mbed-block/BlockDynamic.h`..

**Comment by 0xc0170** [comment]
@marcuschangarm Did you publish mbed-block module?

**Comment by marcuschangarm** [comment]
mbed-block is a private repository. tbh, this repos is not supposed to be public.
